version: '3'
services:
  python:
    image: python-flask
    container_name: python-flask
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-python-flask
    ports:
    - "10100:5000"
    volumes:
    - ./python-flask:/workspace
#    - /etc/group:/etc/group:ro #read only
#    - /etc/passwd:/etc/passwd:ro #read only
    tty: true

  mysql:
    image: mysql
    container_name: mysql
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-mysql
    restart: on-failure
    hostname: my-mysql
    env_file:
      - .env
    environment:
#      MYSQL_USER: sample_user #新たにユーザーを作成する
#      MYSQL_DATABASE: sample_db #新たにDBを作成する
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    expose:
      - "3306"
    ports:
      - "3306:3306"
    # データを永続化させる場合
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir(ホスト側は空のディレクトリをマウントしないと初期データは登録されない！)
      - mysql-data:/var/lib/mysql
    command:
      --secure-file-priv="/docker-entrypoint-initdb.d"
    tty: true
    cap_add:
      - SYS_NICE

  https-portal:
      image: steveltn/https-portal:1
      container_name: https
      ports:
        - '80:80'
        - '443:443'
      environment:
        DOMAINS: 'commentshare.work -> python-flask:5000'
#        STAGE: 'local'
        STAGE: 'staging'
        # STAGE: 'production' # Don't use production until staging works
        # FORCE_RENEW: 'true
      restart: on-failure
      volumes:
        - https-portal-data:/var/lib/https-portal

volumes:
    mysql-data:
    https-portal-data: